chore: use ubi minimal for gosu
Signed-off-by: Maryam Tahhan <mtahhan@redhat.com>

diff --git a/Dockerfile.triton-cpu b/Dockerfile.triton-cpu
--- a/Dockerfile.triton-cpu
+++ b/Dockerfile.triton-cpu
@@ -23,6 +23,7 @@ USER 0
 RUN if [ "$CUSTOM_LLVM" = "true" ]; then \
         dnf update -y && \
         dnf -y install clang rpm-build git ninja-build cmake lld && \
+        dnf clean all && rm -rf /var/cache/dnf && \
         git clone https://github.com/llvm/llvm-project && \
         cd llvm-project && \
         COMMIT=$(curl -s https://raw.githubusercontent.com/triton-lang/triton-cpu/refs/heads/main/cmake/llvm-hash.txt) &&\
@@ -35,26 +36,26 @@ RUN if [ "$CUSTOM_LLVM" = "true" ]; then \
         echo "Skipping LLVM build because CUSTOM_LLVM is not true"; \
     fi
 
-FROM registry.access.redhat.com/ubi9/ubi:latest AS gosu
-
+# gosu Installation Stage
+FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS gosu
 ENV GOSU_VERSION=1.17
-RUN dnf update -y && \
-    dnf -y install wget && \
-    dnf clean all
+RUN microdnf update -y && \
+    microdnf install -y wget && \
+    microdnf clean all && rm -rf /var/cache/dnf
 RUN set -eux; \
-	rpmArch="$(rpm --query --queryformat='%{ARCH}' rpm)"; \
-	case "$rpmArch" in \
-		aarch64) dpkgArch='arm64' ;; \
-		armv[67]*) dpkgArch='armhf' ;; \
-		i[3456]86) dpkgArch='i386' ;; \
-		ppc64le) dpkgArch='ppc64el' ;; \
-		riscv64 | s390x) dpkgArch="$rpmArch" ;; \
-		x86_64) dpkgArch='amd64' ;; \
-		*) echo >&2 "error: unknown/unsupported architecture '$rpmArch'"; exit 1 ;; \
-	esac; \
-	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
-	chmod +x /usr/local/bin/gosu;
+    rpmArch="$(rpm --query --queryformat='%{ARCH}' rpm)"; \
+    case "$rpmArch" in \
+        aarch64) dpkgArch='arm64' ;; \
+        armv[67]*) dpkgArch='armhf' ;; \
+        i[3456]86) dpkgArch='i386' ;; \
+        ppc64le) dpkgArch='ppc64el' ;; \
+        riscv64 | s390x) dpkgArch="$rpmArch" ;; \
+        x86_64) dpkgArch='amd64' ;; \
+        *) echo >&2 "error: unknown/unsupported architecture '$rpmArch'"; exit 1 ;; \
+    esac; \
+    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+    chmod +x /usr/local/bin/gosu && \
+    rm -rf /var/cache/dnf /tmp/*
 
 FROM registry.access.redhat.com/ubi9/python-312 AS base
 ARG CUSTOM_LLVM
@@ -64,7 +65,7 @@ USER 0
 RUN dnf update -y && \
     dnf -y install clang cmake lld ninja-build \
     openblas openblas-devel llvm llvm-libs libomp libomp-devel && \
-    dnf clean all
+    dnf clean all && rm -rf /var/cache/dnf
 
 # Stage for llvm-local-true
 FROM base AS llvm-local-true
